### ISSUE TITLE
Enhance Readme file

### ISSUE THREAD

**Issue by Ayush07571** [Devamani11D/salt-app-kickstart#1]
Hey, I think you could enhance your readme file. please assign this issue some label and assign it to me

**Comment by Devamani11D** [comment]
Yes , Sure!!
Please make sure to mention the project structure and flow of project eg., starting point of application etc.

**Comment by Ayush07571** [comment]
If possible can you assign the label of any level and also hactoberfest accepted

**Comment by Devamani11D** [comment]
Looks great !!
Will do some changes and merge it

**Comment by Devamani11D** [comment]
Ok,

**Comment by Devamani11D** [comment]
Here are the changes, please do all of these and create a PR:
1.Add package-lock.json to generated project structure.
2.In src folder, this is the exact project structure:
![image](https://github.com/user-attachments/assets/fa0cf3f5-73d5-459d-9d43-69e067468e20)

3.First mention the current project structure and then generated project structure and label the correct heading.
4.In current project structure , index.js and index.html are the files to be copied to the generated project.Change the description there and in the flow chart also:
![image](https://github.com/user-attachments/assets/3e28fbf8-4b50-485c-83c6-b6644c92d7eb)
![image](https://github.com/user-attachments/assets/9b6fc45d-c00b-4ac3-a851-90299a7e5bc9)

5.Here write that, cli.js has command's abstract logic...
![image](https://github.com/user-attachments/assets/5f345854-ee3a-4594-9810-bc718857e490)

**Comment by Ayush07571** [comment]
@Devamani11D Kindly once check now, I have updated my PR #6 . I have some modifications as suggested by you.
