### ISSUE TITLE
terminate the process on CTRL-C or CTRL-D

### ISSUE THREAD

**Issue by nikhilkalburgi** [Devamani11D/salt-app-kickstart#11]
**Current behavior:**

The process continues to execute after it is terminated:
![image](https://github.com/user-attachments/assets/d5a92230-68eb-491d-a34f-5f8011eb6391)

**Expected behavior:**

It should terminate with a message printed like:

```
// Inside catch
console.log(chalk.red(`Process has been terminated. ${error.message}`));
```

**Comment by adityakalburgi** [comment]
@nikhilkalburgi i will do this

**Comment by Devamani11D** [comment]
@adityakalburgi ,
Please go ahead with the work!!Assigning it to you!

**Comment by Devamani11D** [comment]
@nikhilkalburgi , I dont know whether it can be assigned level3, Can you please look into it once!

**Comment by nikhilkalburgi** [comment]
Hi @Devamani11D, I added this considering the work that is required to analyse the code and do the change. But, if you think the level should be less then feel free to change it. 

By the way, I have updated the levels name to what GSSoC wants us to have. Have a look at it as well. See if any other thing is pending.

**Comment by Devamani11D** [comment]
Hey @nikhilkalburgi , Can i please know how to correct or add the labels to any project in which i am a collaborator in that project but i cannot see that settings icon to add topics to the project.

**Comment by nikhilkalburgi** [comment]
Hi @Devamani11D , I changed it in the labels section that comes beside any issue page. Click on the settings icon on the labels section. Then you will get options to add new labels + one last option to edit or create new labels.
