### ISSUE TITLE
ADD: Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [Devamani11D/salt-app-kickstart#15]
**Description:**
I propose to implement a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.

**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
  - **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
  - **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

Hey @Devamani11D Please assign this task to me

**Comment by Devamani11D** [comment]
Hey @samyak-aditya ,
Thank you for your interest in contributing to the project!!
This idea is very good!! But Can you also please have a look at issue #14 and see if they are related. If so i can assign the issues to both of you. And you both can work on it.

**Comment by samyak-aditya** [comment]
Hey @Devamani11D that issue is different from mine 
You can assign me this task

**Comment by Devamani11D** [comment]
Yes @samyak-aditya !
I have gone through implemenetation flow now. Both the issues are different. Thank you for bringing it into notice! :tada:

**Comment by samyak-aditya** [comment]
Hey @Devamani11D I have raised the PR
thanks
