### ISSUE TITLE
Add Frequently used templates to templates folder

### ISSUE THREAD

**Issue by Devamani11D** [Devamani11D/salt-app-kickstart#2]
* Create frontend templates using the [Salt Design System](https://www.saltdesignsystem.com/salt/index).
*   These templates would serve as starting points for new applications.

**Comment by adityakalburgi** [comment]
@Devamani11D  i would like to create a login in template using salt design system please assign this issue to me and also add gssoc-exd label thank you..

**Comment by Devamani11D** [comment]
Heyyy!
Glad to know that!
Will be assigning this issue to you soon. Start working on it.

**Comment by Devamani11D** [comment]
@adityakalburgi , assigned the issue to you. As it is about useful templates , I may assigned to a set of people, So please be clear about the design of the template and be active in mentioning it here in early stage, so that no one repeats the template design.

**Comment by adityakalburgi** [comment]
@Devamani11D Thank you for assigning the issue! I will focus on designing the login template only. I'll ensure the design details are shared early in the process so that there's no duplication of efforts. I'll actively provide updates and discuss any potential overlaps to maintain clarity among the team.

**Comment by Devamani11D** [comment]
Yeah, Sure !!
Thank you @adityakalburgi

**Comment by adityakalburgi** [comment]
Hi @Devamani11D i have submitted a PR please have a look..

**Comment by Bhuvana145** [comment]
I want to work on this. Please assign to this to me

**Comment by Devamani11D** [comment]
Hey assigning the issue to you!!
Please make all the templates to follow same theme!
thank you 🥇

**Comment by Devamani11D** [comment]
Create a new issue,I will assign it to you

**Comment by adityakalburgi** [comment]
Hi! @Devamani11D is someone intrested to change the style of other templetes similar to login template or should i do it?..

**Comment by Devamani11D** [comment]
U can go ahead aditya 
:rocket:

**Comment by adityakalburgi** [comment]
Ok👍

> U can go ahead aditya 🚀
