### ISSUE TITLE
Add: "auto-label" GitHub Workflow for Automated Labeling

### ISSUE THREAD

**Issue by samyak-aditya** [Devamani11D/salt-app-kickstart#20]
**Objective:** Implement an "auto-label" GitHub workflow to automatically assign the "gssoc-ext" and "hacktoberfest-accepted" labels to relevant pull requests and issues.

**Details:**

- This workflow will streamline the labeling process by automatically applying the "gssoc-ext" and the "hacktoberfest-accepted" label to Issues.
- By automating these labels, we can ensure consistent tracking and visibility of contributions tied to these significant events.

Implementing this "auto-label" workflow will enhance project organization 

Hey @Devamani11D  Please assign it to me with label "level3"

**Comment by Devamani11D** [comment]
Hey !
This idea is quite good. Let's work on it together. I am very happy to collaborate with you!! 🚀

**Comment by samyak-aditya** [comment]
Hey @Devamani11D I have raised the PR
