### ISSUE TITLE
Github Workflow : Notify Contributors When Pull Requests Are Merged

### ISSUE THREAD

**Issue by samyak-aditya** [Devamani11D/salt-app-kickstart#23]
I would like to work on the workflow you requested 

Notify Contributors When Pull Requests Are Merged

### Issue Description
**Background:**
Currently, when a pull request (PR) is merged, contributors are not notified about the status of their contributions. It’s important to acknowledge their efforts and keep them informed to foster a positive and collaborative environment.

**Benefits:**
- Enhances contributor engagement.
- Acknowledges their work, which can encourage future contributions.
- Improves communication within the project.

Hey @Devamani11D Please assign me this issue with "level3"

**Comment by Devamani11D** [comment]
Hey @samyak-aditya ,
Issue assigned to you!! Please go ahead.

**Comment by samyak-aditya** [comment]
Hey @Devamani11D I have raised the PR
