### ISSUE TITLE
Check and Modify auto_label.yml file in .github -> workflows.

### ISSUE THREAD

**Issue by Devamani11D** [Devamani11D/salt-app-kickstart#29]
Label PR is not working

**Comment by Ramharsh-aidev** [comment]
Hello @Devamani11D ,
I would like to express my interest in working on the auto_label.yml project within the GitHub workflows. I believe that enhancing the automation of issue labeling could significantly improve our workflow efficiency.
Could you please assign this project to me? I’m eager to dive into the details and contribute to its development. If there are specific areas you want me to focus on, please let me know.
Thank you for considering my request. I look forward to your response!

**Comment by Devamani11D** [comment]
@Ramharsh-aidev 
Thank you for your interest. Assigning it to you with level2.
But as i am assigning level 2 to it, please also consider doing other automation task possible in this project. 
Thank you 🚀

**Comment by Ramharsh-aidev** [comment]
Thank you for assigning this issue to me I will start working on it. And try to fix it as soon as possible

**Comment by Ramharsh-aidev** [comment]
Sir I had created the pull request using other Account with username @RamharshDandekar 
As I was getting problem during creating pull request using this account

So please review that pull request

**Comment by Devamani11D** [comment]
Closing this issue as this is completed by you  and PR is being raised from another account by you
