### ISSUE TITLE
Adding All Contributor's Profile Photos

### ISSUE THREAD

**Issue by say-het** [Devamani11D/salt-app-kickstart#32]
### **Issue Description**

 - It lacks Contributors Profiles in Readme.md
 - It should be Like the image that I have shared
 - Hey! @Devamani11D I have already fixed it. Can you assign me this issue under GSSoC-Extd so that I can raise a PR.

 - Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020, Hacktoberfest-2023 and GSSoC-2024.

 **I will add this type of Live Contributor Profile Photos in it**
![image](https://github.com/user-attachments/assets/c109d3d6-a375-493e-a01b-aaf9370d603c)

**Comment by shaswat-satyam** [comment]
Can you assign this issue to me?

**Comment by Devamani11D** [comment]
@say-het assigned to you

**Comment by Devamani11D** [comment]
> Can you assign this issue to me?

Hey sorry!!
As @say-het  has first raised the issue and wanna work on it, i have assigned it to him. Please have a look at other issues and we appreciate your willingness to contribute. :rocket:

**Comment by Devamani11D** [comment]
Hey @say-het it's better if the first image is full and other images are on top of each other , like they appear only half round image

**Comment by say-het** [comment]
Ya that would look good but it won't update live, as I would have to do it for each contributor, so the one that I have attached in image would be better.

**Comment by Devamani11D** [comment]
Oh ok @say-het , Continue with your approach.
But can i know why it can't be updated live, as it is matter of fronted when it comes to how we want to display or showcase.
Thank you 😄

**Comment by Devamani11D** [comment]
Please complete the work asap, as gssoc is going to end soon and your points would have impact on leaderboard after that.
thank you 😄

**Comment by Devamani11D** [comment]
Very sorry for closing this issue. I will be busy in the last few days of GSSoC and had to wind up this project so that i can showcase it well. So i have added it myself in readme.
Thank you for your cooperation. 😃

**Comment by Devamani11D** [comment]
Closing this issue
