### ISSUE TITLE
Notice - Gssoc Ext Request to Add Missing Labels on Merged PRs  

### ISSUE THREAD

**Issue by Meetjain1** [Devamani11D/salt-app-kickstart#33]
Hi @Devamani11D 

We have noticed that some **merged PRs** in your project are missing important labels, Adding proper labels is essential to ensure contributors receive accurate points on the **leaderboard** and maintain clarity in the contribution process.  

We kindly request you to **review all merged PRs** and ensure that **each PR is labeled correctly**. This will avoid any confusion or discrepancies in contributors' points and help maintain smooth project management.  

Thank you for your cooperation!  

Best regards,  
GSSoC Extended Core Team

**Comment by Devamani11D** [comment]
Sure @Meetjain1 , Thank you for bringing it into our notice. We will make sure that all necesaary labels are added to the merged PR's 😄
