### ISSUE TITLE
add ci cd workflow

### ISSUE THREAD

**Issue by ananyag309** [Devamani11D/salt-app-kickstart#34]
CI/CD Workflow
Automate build, test, and deployment of your project:

On every push or pull request, trigger unit tests and build the project.

**Comment by Devamani11D** [comment]
@ananyag309  , The build and tests on node env are failed.
Can you please look into this issue??

**Comment by ananyag309** [comment]
@Devamani11D yes sure let me check

**Comment by Devamani11D** [comment]
ok , Thank you @ananyag309 
😄

**Comment by Devamani11D** [comment]
Can you please raise PR again with required changes
@ananyag309

**Comment by ananyag309** [comment]
yes sure
