### ISSUE TITLE
Character Length Validation for Username and Password:

### ISSUE THREAD

**Issue by ananyag309** [Devamani11D/salt-app-kickstart#35]
You could add validation to ensure that both the username and password meet a minimum character length before submission.

**Comment by BarryByte** [comment]
@Devamani11D  Please assign me this issue ...

**Comment by Devamani11D** [comment]
@BarryByte Assigning it to you 😄

**Comment by ananyag309** [comment]
@Devamani11D i raised this issue please assign it to me. till now no issue is assigned to me on this repo
