### ISSUE TITLE
Loading State for the Submit Button

### ISSUE THREAD

**Issue by ananyag309** [Devamani11D/salt-app-kickstart#36]
Introduce a loading state to provide feedback when the form is being submitted.

**Comment by BarryByte** [comment]
@Devamani11D Please assign me this issue.

**Comment by Devamani11D** [comment]
Yes , But loading icon should appear only for sometime and then the form should appear again with a toast showing "The form is submitted successfully"
Thank you @BarryByte 😄 @ananyag309

**Comment by ananyag309** [comment]
@Devamani11D 
yes i want to work on it
