### ISSUE TITLE
Error Handling in login.js

### ISSUE THREAD

**Issue by ananyag309** [Devamani11D/salt-app-kickstart#37]
Implement error handling to show error messages when the login fails.

**Comment by career-yashaswee** [comment]
Sure, it's an easy fix, would love to work upon this!

**Comment by Devamani11D** [comment]
Hey
At present , we don't have backend for the generated project , it's simply a react project.So if you have any other ideas, we can move further.
@ananyag309  @career-yashaswee

**Comment by career-yashaswee** [comment]
Sure could do that!

**Comment by momithalasya** [comment]
I would love to take on this task and ensure that we provide clear and helpful error messages for users.
Please let me know if you can assign this issue to me. I’m looking forward to contribute!
Thank you!
