### ISSUE TITLE
[Feature] Addition of Carousel Template

### ISSUE THREAD

**Issue by PrityanshuSingh** [Devamani11D/salt-app-kickstart#48]
### 📋 Description

Create a reusable carousel component using `react-slick`, supporting configurations like `autoplay`, `fade`, `slidesToShow`, and arrows. It will allow arrow designs (e.g., bold arrows `❮`, `❯`) with color, and background. The component should dynamically render content such as text, images, or div containers and ensure full responsiveness with touch support. Default styling will be provided, with options for easy customization.

### 🔧 Additional Information

We will use `react-slick` and `slick-carousel` for dependencies to provide robust carousel functionality. The component should integrate smoothly into different projects.

Please assign this issue to me under gssoc-ext level3 and hactoberfest-accepted, @Devamani11D  , as I am interested in working on it.

**Comment by Devamani11D** [comment]
Hey!!
Once check if you can do it using salt-design system.

**Comment by PrityanshuSingh** [comment]
Thank you @Devamani11D , for pointing that out! I realized that we don’t need react-slick or any external package to build a carousel. We can implement it using Salt Design components and custom logic without making the project unnecessarily heavy. I’m interested in taking on this task. Please assign the issue to me under gssoc-ext level3 and hacktoberfest-accepted.
