### ISSUE TITLE
 Error Handling for Email Input

### ISSUE THREAD

**Issue by ananyag309** [Devamani11D/salt-app-kickstart#52]
The current implementation of the email input lacks robust error handling, which may lead to user frustration if they enter invalid email formats. By integrating real-time validation and displaying specific error messages, we can enhance user experience and ensure that users provide accurate information before form submission. This improvement will not only guide users effectively but also reduce submission errors and increase overall form reliability.

**Comment by sikehish** [comment]
Could you assign this to me? I'd like to take this up

**Comment by Devamani11D** [comment]
Hi @ananyag309 ,
Please raise all related issues under one issue so that i can give correct labelling.
Thank you 👍
