### ISSUE TITLE
Adding  -y option to salt-app-kickstart command

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Devamani11D/salt-app-kickstart#53]
- CLI option `-y` should accept all default prompts without interaction, simplifying the setup for advanced users.

**Comment by mehul-m-prajapati** [comment]
@Devamani11D : please assign this to me.

**Comment by Devamani11D** [comment]
yes assigning to you @mehul-m-prajapati 🚀

**Comment by Devamani11D** [comment]
Please complete the work asap, as gssoc is going to end soon and your points would have impact on leaderboard after that.
thank you 😄
