### ISSUE TITLE
Adding Database Selection option in command prompt

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Devamani11D/salt-app-kickstart#54]
```
{
    type: 'list',
    name: 'databaseChoice',
    message: 'Which database would you like to use?',
    choices: ['PostgreSQL', 'MongoDB', 'MySQL', 'SQLite', 'None'],
    default: 'PostgreSQL',
},
```

**Comment by Devamani11D** [comment]
cool !!
but how are you going to proceed with the result. You should also configure the setup of that database right , but as this is related to providing most frequently used UI's and using salt-design system it doesn't fit here. Otherwise the idea is good.

**Comment by mehul-m-prajapati** [comment]
Okay, sounds good.
