### ISSUE TITLE
[FEATURE]: ADD Notification TOASTER SYSTEM

### ISSUE THREAD

**Issue by shubhagarwal1** [Devamani11D/salt-app-kickstart#56]
**Notification System**
Implement a notification system that can display various types of messages (success, error, info) in a toast format. Allow for customization of duration, position, and actions.

**Proposed Idea**
- Default styling will be provided, and the component will be designed to allow easy customization through props or CSS classes to fit various design themes.
- Incorporate a simple event system to manage notifications, allowing developers to trigger notifications easily throughout their applications.

Hey @Devamani11D please assign this task to me

**Comment by Devamani11D** [comment]
Great !
Assigning it to you @shubhagarwal1
