### ISSUE TITLE
Add auto-comment functionality for issue open/close via autocomment-issue-open-closed.yml

### ISSUE THREAD

**Issue by ananyag309** [Devamani11D/salt-app-kickstart#57]
Create an autocomment-issue-open-closed.yml file to automate commenting on GitHub issues when they are opened or closed. This will ensure that every issue receives a predefined response for better communication and tracking.

**Comment by Devamani11D** [comment]
this is already implemented in github workflows and please have a look and confirm if is the same.
thank you
