### ISSUE TITLE
[FEATURE] Integrate a Chatbot for Instant User Support

### ISSUE THREAD

**Issue by sezallagwal** [Devamani11D/salt-app-kickstart#63]
Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

please assign this to me under gssoc-ext and hacktoberfest

**Comment by Devamani11D** [comment]
Ok . I am assigning the issue to u.
Please go ahead 😄

**Comment by Devamani11D** [comment]
Please complete the work as soon as possible . because GSSOC is ending soon and your marks wont count after this.
thank you

**Comment by sezallagwal** [comment]
okay wait I'm raising the pr within a hour @Devamani11D

**Comment by sezallagwal** [comment]
@Devamani11D any updates?
