### ISSUE TITLE
[Feature] Implement Reusable Accordion Component Using Salt Design System

### ISSUE THREAD

**Issue by PrityanshuSingh** [Devamani11D/salt-app-kickstart#66]
### 📋 Description
Create a reusable accordion component using the Salt Design System, supporting configurations like expandable/collapsible functionality, customizable headers, and dynamic content rendering. The accordion should accommodate various content types, including text, images, and other React components, ensuring full responsiveness and accessibility features. Default styling will be provided, with options for easy customization to match different design needs.

### 🔧 Additional Information
- The component should integrate smoothly into different projects without relying on external libraries.
- Provide customization options for colors, fonts, and animations for opening and closing actions.
- Ensure that the accordion maintains accessibility standards, allowing keyboard navigation and screen reader support.

Please assign this issue to me under gssoc-ext level3 and hacktoberfest-accepted, @Devamani11D, as I am interested in working on it.

**Comment by Devamani11D** [comment]
Please use the theme(colors) of the navbar. Don't use other themes as it should be same.
Thank you
