### ISSUE TITLE
[Feature] Implement Reusable Calendar Component Using Salt Design System

### ISSUE THREAD

**Issue by PrityanshuSingh** [Devamani11D/salt-app-kickstart#69]
📋 ### Description
Create a reusable calendar component using the Salt Design System, supporting basic date display, selection functionality, and configurable views (monthly, weekly, daily). The component should accommodate dynamic content updates for selected dates and ensure full responsiveness. Default styling will be provided, with options for customization to match various design requirements.

🔧 ### Additional Information 
- The component should integrate seamlessly into different projects without relying on external libraries.  
- Provide customization options for colors, fonts, and date formats.  
- Ensure accessibility standards are maintained, including keyboard navigation and screen reader support.  

@Devamani11D , Please assign this issue to me under gssoc-ext level3 and hacktoberfest-accepted.

**Comment by Devamani11D** [comment]
Ofcourse i will assign you with level 3 buddy. No need to specify. 😄

**Comment by PrityanshuSingh** [comment]
> Ofcourse i will assign you with level 3 buddy. No need to specify. 😄

Haha thnks bud, i have a doubt is it necessary to label tags in the PR too? or the points in gssoc gets upgraded from the issue labels only?
