### ISSUE TITLE
auto play video in readme file

### ISSUE THREAD

**Issue by Devamani11D** [Devamani11D/salt-app-kickstart#73]
Now , user or contributor has to click on the video thumbnail and it open in new tab to play video. Make the video to autoplay at its current position.
will assign this issue with level 3, so whoever is interested can work on it.

**Comment by PrityanshuSingh** [comment]
@Devamani11D assign me this issue

**Comment by PrityanshuSingh** [comment]
@Devamani11D  kindly update about the status of this issue as today is the last day for gssoc-ext PRs.
