### ISSUE TITLE
add index.html to public folder

### ISSUE THREAD

**Issue by nikhilkalburgi** [Devamani11D/salt-app-kickstart#8]
Currently, the tool is adding `index.html` to `src` folder. This is not the right location for this file. Update the logic in the code to make it overwrite the original `index.html` file in `public` folder.

See this screenshot:
![image](https://github.com/user-attachments/assets/983cffb2-4502-49d0-8d91-757944c709e6).

**Comment by Devamani11D** [comment]
Yes @nikhilkalburgi , You are right!!
I will be glad to assign this issue to you. Also Don't forget to modify the content of the file , especially the content attribute in meta tag should be "Website created using salt-app-kickstart".
Here is the Screenshot for reference:
![image](https://github.com/user-attachments/assets/c00e1f40-6bba-46c7-b714-a72b1da6fb30)

**Comment by jaishsingh** [comment]
can you assign this code?

**Comment by nikhilkalburgi** [comment]
Hi @jaishsingh , go ahead!

**Comment by Devamani11D** [comment]
> can you assign this code?

Yes @jaishsingh , Please go ahead !!

**Comment by jaishsingh** [comment]
No

**Comment by adityakalburgi** [comment]
please assign this issue to me i will do it ! @nikhilkalburgi

**Comment by jaishsingh** [comment]
go ahead
