### ISSUE TITLE
add fancy text to the start of the prompt in terminal

### ISSUE THREAD

**Issue by nikhilkalburgi** [Devamani11D/salt-app-kickstart#9]
It looks very attractive when a fancy text like "Salt App Design" appears in the beginning of the prompt.

Example:

![image](https://github.com/user-attachments/assets/ddedf9da-fdc0-44d9-aa00-72186d154b9c)

This can be achieved using the lib like [cfont ](https://www.npmjs.com/package/cfonts)

**Comment by adityakalburgi** [comment]
@nikhilkalburgi please have a look i have submitted a PR.
